version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ecommerce
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  user-service:
    build: .
    container_name: user_service
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
      DB_NAME: ecommerce
      DB_PORT: 5432
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge
