version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  db_data:
